import { NAMESPACE_COMMON } from '../../../consts';

export const COMMON_MODAL_OPEN = `${NAMESPACE_COMMON}/COMMON_MODAL_OPEN`;
export const COMMON_MODAL_CLOSE = `${NAMESPACE_COMMON}/COMMON_MODAL_CLOSE`;
