import { NAMESPACE_CART } from '../../consts';

export const GET_CART = `${NAMESPACE_CART}/GET_CART`;
export const REQUEST_ADD_TO_CART = `${NAMESPACE_CART}/REQUEST_ADD_TO_CART`;
export const ADD_TO_CART = `${NAMESPACE_CART}/ADD_TO_CART`;
export const DELETE_CART = `${NAMESPACE_CART}/DELETE_CART`;
export const UPDATE_CART_ONE = `${NAMESPACE_CART}/UPDATE_CART_ONE`;
export const UPDATE_CART_MULTI = `${NAMESPACE_CART}/UPDATE_CART_MULTI`;
