import { NAMESPACE_REDDIT_API } from '../../consts';

export const REQUEST_POSTS = `${NAMESPACE_REDDIT_API}/REQUEST_POSTS`;
export const RECEIVE_POSTS = `${NAMESPACE_REDDIT_API}/RECEIVE_POSTS`;
export const REQUEST_POSTS_FAILE = `${NAMESPACE_REDDIT_API}/REQUEST_POSTS_FAILE`;
export const SELECT_REDDIT = `${NAMESPACE_REDDIT_API}/SELECT_REDDIT`;
export const INVALIDATE_REDDIT = `${NAMESPACE_REDDIT_API}/INVALIDATE_REDDIT`;
